name: Mocha-Tests

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: [4.2]

    steps:
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      # - name: Start mongodb
      #   run: mongod --fork --logpath /var/log/mongod.log

      - name: Create keys
        run: |
          cd keys
          openssl genrsa -out private.pem 512
          openssl rsa -in private.pem -outform PEM -pubout -out public.pem
          openssl genrsa -out privater.pem 512
          openssl rsa -in privater.pem -outform PEM -pubout -out publicr.pem

      - name: Get repo secrets into environment file
        run: |
          touch .env
          echo "${{ SECRETS.ENV_VARS_LOCALHOST }}" >> .env

      - run: npm ci

      - name: Install dependencies
        run: npm install

      #    - run: npm run build --if-present
      - run: npm test
